package.json

Add missing version bumps from 0.1.0 to 0.1.5

build: version bump to v0.1.1

---

package.json
src/features/create-token/CreateToken.module.scss
src/features/create-token/CreateToken.types.ts
src/features/create-token/CreateTokenBody.tsx
src/features/create-token/CreateTokenButton.tsx
src/features/create-token/CreateTokenForm.tsx
src/features/create-token/CreateTokenHeader.module.scss
src/features/create-token/CreateTokenHeader.tsx
src/features/create-token/CreateTokenModal.tsx
src/features/create-token/index.ts
src/features/create-token/steps/DetailsForm.module.scss
src/features/create-token/steps/DetailsForm.test.tsx
src/features/create-token/steps/DetailsForm.tsx
src/features/create-token/steps/TokenSummary.module.scss
src/features/create-token/steps/TokenSummary.test.tsx
src/features/create-token/steps/TokenSummary.tsx
src/features/create-token/steps/TokenSummaryField/TokenSummaryField.module.scss
src/features/create-token/steps/TokenSummaryField/TokenSummaryField.tsx
src/features/create-token/steps/TokenomicsForm.module.scss
src/features/create-token/steps/TokenomicsForm.test.tsx
src/features/create-token/steps/TokenomicsForm.tsx
src/features/ui/WrappedInput/WrappedInput.module.scss
src/features/ui/WrappedInput/WrappedInput.tsx

[Wizard setup](https://www.notion.so/rational-nomads/Wizard-setup-e89ce4c065004ea09ee3d789db4b9341)
[Token Launcher Details Step](https://www.notion.so/rational-nomads/Token-Launcher-Details-Step-9efd229b6e1c4c5f889c5920368ce8ed)
[Token Launcher Tokenomics Step](https://www.notion.so/rational-nomads/Token-Launcher-Tokenomics-Step-0f3416d06ae841dcada280a0fac6c4bc)
[Token Launcher Launch Step](https://www.notion.so/rational-nomads/Token-Launcher-Launch-Step-84b04d70d5704e61befb8eb18d16ee86)
zUI changes:
https://github.com/zer0-os/zUI/pull/27
-----
```
- Feature
```
No token launcher modal.
Introduction of the create token launcher modal and shared Wrapped Input component.

feat: token launcher wizard setup

---

package-lock.json
package.json
src/App.module.scss
src/App.tsx
src/features/domain-preview/DomainPreview.tsx
src/features/ui/StatsList/StatsList.tsx
src/features/view-subdomains/SubdomainMetrics/SubdomainMetrics.tsx
src/features/view-subdomains/SubdomainTable/SubdomainTable.tsx
src/features/view-subdomains/SubdomainTable/SubdomainTableItem.tsx
src/features/view-subdomains/SubdomainTableCard/SubdomainTableCard.module.scss
src/features/view-subdomains/SubdomainTableCard/SubdomainTableCard.tsx
src/features/view-subdomains/SubdomainTableRow/SubdomainTableRow.tsx
src/features/view-subdomains/useSubdomainData.ts
src/lib/constants/networks.ts
src/lib/providers/ZnsSdkProvider.tsx
src/pages/Domains/Domains.tsx

Pushing a whole bunch of changes to prep for initial PR into zOS.

feat: various changes for migration

---

jest.setup.ts
src/features/create-token/steps/DetailsForm.test.tsx
src/features/create-token/steps/TokenSummary.test.tsx
src/features/create-token/steps/TokenomicsForm.test.tsx
src/features/transfer-ownership/TransferOwnershipForm/TransferOwnershipForm.test.tsx

- fixes for the following test/jest errors resulting from components that import from `zUI`

fix: resolve breaking feature tests that use zUI imports

---

src/App.tsx
src/features/domain-preview/DomainPreview.module.scss
src/features/domain-preview/DomainPreview.tsx
src/features/view-nft/Actions/Actions.tsx
src/features/view-nft/HistoryList/HistoryList.tsx
src/features/view-nft/NFTMetrics/NFTMetrics.tsx
src/features/view-nft/TokenHashInfo/TokenHashInfo.tsx
src/features/view-subdomains/SubdomainMetrics/SubdomainMetrics.tsx
src/features/view-subdomains/SubdomainTable/SubdomainTable.tsx
src/lib/hooks/useDataContainer.ts
src/pages/Domains/Domains.tsx
src/pages/NFT/NFT.tsx

Aim to reduce amount of props and drilling.
Make use of `useDataContainer()` hook throughout.

feat: reduce props

---

.scripts/link.sh
package.json
src/features/create-dao/CreateDAO.types.ts
src/features/create-dao/CreateDAOBody.tsx
src/features/create-dao/CreateDAOButton.tsx
src/features/create-dao/CreateDAOForm.module.scss
src/features/create-dao/CreateDAOForm.tsx
src/features/create-dao/CreateDAOFormContext.tsx
src/features/create-dao/CreateDAOHeader.module.scss
src/features/create-dao/CreateDAOHeader.tsx
src/features/create-dao/CreateDAOModal.tsx
src/features/create-dao/index.ts
src/features/create-dao/steps/DAOSummary.module.scss
src/features/create-dao/steps/DAOSummary.tsx
src/features/create-dao/steps/DetailsForm.module.scss
src/features/create-dao/steps/DetailsForm.test.tsx
src/features/create-dao/steps/DetailsForm.tsx
src/features/create-dao/steps/GovernanceForm.module.scss
src/features/create-dao/steps/GovernanceForm.tsx
src/features/create-dao/steps/TreasuryForm.module.scss
src/features/create-dao/steps/TreasuryForm.tsx
src/features/create-dao/steps/index.ts

[DAO Launcher modal setup](https://www.notion.so/rational-nomads/DAO-Launcher-modal-setup-12d3273fc88d4ba1af1287bc76f82dc9)
[DAO Launcher Details step](https://www.notion.so/rational-nomads/DAO-Launcher-Details-Step-99bc5fbca3ae4976b25a7218fa9346e9)
-----
```
- Feature
```
No DAO Launcher modal.
Introduction of the create DAO launcher modal.

feat: dao launcher wizard setup

---

package.json
src/features/ui/StatsList/StatsList.tsx
src/features/view-nft/NFTMetrics/NFTMetrics.tsx
src/features/view-nft/TokenHashInfo/TokenHashInfo.module.scss
src/features/view-nft/TokenHashInfo/TokenHashInfo.tsx
src/features/view-subdomains/SubdomainMetrics/SubdomainMetrics.tsx
src/lib/constants/ipfs.ts
src/lib/helpers/network.ts
src/lib/hooks/useDataContainer.ts
src/lib/util/domains/domains.ts
src/lib/util/ipfs.ts/ipfs.ts

[Associated Notion Card](https://www.notion.so/zerotech/zApp-NFTs-feedback-23ea6711e50f4cba8e3b62ce148e49e5?p=63319318fd874101bb51c1c9909e427a&pm=s)
-----
- bug fix
- refactoring
Currently no handling of loading on metrics
Currently no handling of token / hash boxes
'ERR' text on metrics
No arrow links for etherscan link or ipfs url
Added arrow links for etherscan link or ipfs url
Handling of loading on metrics - skeleton
Handling of loading on token / hash boxes
Handle error text on metrics

refactor: improve metrics loading and error

---

src/features/view-nft/Action/Action.module.scss
src/features/view-nft/Actions/Actions.module.scss

[Associated Notion Card](https://www.notion.so/zerotech/zApp-NFTs-feedback-23ea6711e50f4cba8e3b62ce148e49e5?p=156c9e18e66d48a6b881c4900858501d&pm=s)
-----
- bug fix (ui)

fix: fix alignment of action buttons

---

package-lock.json
src/features/domain-preview/DomainPreview.module.scss
src/features/domain-preview/DomainPreview.tsx
src/features/view-nft/HistoryItem/HistoryItem.module.scss
src/features/view-nft/HistoryList/HistoryList.module.scss
src/features/view-nft/HistoryList/HistoryList.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Prevent-text-load-making-content-jump-around-838d47fd3da743e2a60c01070a865f2b)
-----
Feature.
Some text was loading the "old way", i.e. don't render until it loads.
https://user-images.githubusercontent.com/12437916/196321425-e5ea89d8-093f-4ee8-8d20-e67c6761b29e.mov
Replaces the "old way" of loading text with `SkeletonText` for a smoother loading experience.
https://user-images.githubusercontent.com/12437916/196321710-3c00e947-c7a9-4be0-b818-af609dc01bce.mov

feat: add skeleton text

---

src/features/create-dao/CreateDAOHeader.tsx
src/features/create-token/CreateTokenHeader.tsx

- quick PR to update outdated icon imports that are causing failing tests

fix: update outdated icon imports

---

package-lock.json
package.json
src/features/view-nft/Actions/Actions.tsx
src/features/view-nft/HistoryItem/HistoryItem.tsx
src/features/view-nft/HistoryList/HistoryList.tsx
src/features/view-nft/NFTMetrics/NFTMetrics.tsx
src/features/view-subdomains/SubdomainMetrics/SubdomainMetrics.tsx
src/features/view-subdomains/useSubdomainTableItem.ts
src/lib/hooks/useDomainData.ts
src/lib/hooks/usePaymentToken.ts
src/lib/hooks/useSubdomainData.ts

[Associated Notion Card #1](https://www.notion.so/zerotech/Domains-with-many-subdomains-not-loading-subdomains-0716ae6e18a64bdf8b878d9347ef9927)
[Associated Notion Card #2](https://www.notion.so/zerotech/Use-token-symbol-rather-than-token-name-7f66a04839af46feba6bd35a4a20122d)
-----
Feature / Bug Fix
- `wilder.wheels.genesis` and other long subdomain lists weren't loading.
- Was using token name (`Wilder`) instead of token symbol (`WILD`).
- Long subdomain lists load.
- Using token symbol.

fix: long domain loading & token symbol

---

package-lock.json
package.json
src/App.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Handle-app-scrolling-68d9fe189c2c4905b069e565ac4f5349)

fix: scrollbar shouldn't push content left

---

package-lock.json
package.json
src/features/view-subdomains/SubdomainTableCard/SubdomainTableCard.tsx

[Associated Notion Card](https://www.notion.so/zerotech/GridCard-onClick-should-take-event-data-as-a-parameter-c519e9bbac4645ccbc4c4cb7eee6eefc)

fix(subdomain-card): click modal shouldn't fire card click

---

package-lock.json
package.json

[Associated Notion Card](https://www.notion.so/zerotech/Images-not-loading-in-Chrome-Brave-6752d77ae9644dfdbf128c55405903e9)
Fixed in `zApp-utils`, bumped version number in `zApp-NFTs`

fix: IpfsImage not loading in Chrome

---

src/features/view-subdomains/SubdomainTableCard/SubdomainTableCard.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Subdomain-grid-card-images-don-t-load-for-NFTs-which-have-a-video-as-their-metadata-image-field-9a55a5d037bf4f448cf10af6fa10fbfc)
Needed to handle `image` metadata a bit differently, as `image` is sometimes actually a video

fix(subdomain-table): broken card image for some domains

---

package.json

- Addition of Accept Bid / View Bids feature 
`0.5.2` => `0.6.0`

chore: bump version (`0.5.2` -> `0.6.0`)

---

package-lock.json
package.json

Individual Build Previews

---

src/features/view-nft/NFTBannerContainer/NFTBannerContainer.module.scss
src/features/view-nft/NFTBannerContainer/NFTBannerContainer.tsx

Some quick fixes to the NFT page for iterative deployment:
- Added red radial gradient on NFT page.
- Align/size images on NFT page.

feat(view-nft): add radial gradient, align media

---

package.json

chore: bump version (`0.6.0` -> `0.7.0`)

---

src/App.tsx
src/features/accept-bid/AcceptBidForm/FormSteps/Confirm/Confirm.tsx
src/features/accept-bid/AcceptBidForm/FormSteps/ui/NFTDetails/NFTDetails.tsx
src/features/accept-bid/AcceptBidForm/hooks/useAcceptBidForm.tsx
src/features/accept-bid/useAcceptBidData.ts
src/features/cancel-bid/CancelBidForm/CancelBidForm.tsx
src/features/cancel-bid/CancelBidForm/FormSteps/Complete/Complete.tsx
src/features/cancel-bid/CancelBidForm/hooks/useCancelBidForm.tsx
src/features/cancel-bid/useCancelBidData.ts
src/features/place-bid/PlaceBidForm/FormSteps/Confirm/Confirm.tsx
src/features/place-bid/PlaceBidForm/FormSteps/Details/Details.tsx
src/features/place-bid/PlaceBidForm/FormSteps/hooks/useFormSteps.tsx
src/features/place-bid/PlaceBidForm/FormSteps/ui/NFTDetails/NFTDetails.tsx
src/features/place-bid/PlaceBidForm/hooks/usePlaceBidForm.tsx
src/features/place-bid/usePlaceBidData.ts
src/features/transfer-ownership/TransferOwnershipForm/hooks/useTransferOwnershipForm.tsx
src/features/transfer-ownership/useTransferOwnershipData.ts
src/features/view-bids/ViewBids.module.scss
src/features/view-bids/ViewBids.tsx
src/features/view-bids/useViewBidsData.ts
src/features/view-nft/HistoryList/HistoryList.tsx
src/features/view-nft/NFTDetailsCard/NFTDetailsCard.tsx
src/features/view-nft/NFTDetailsCard/ui/Options/Options.tsx
src/features/view-nft/NFTMetrics/NFTMetrics.tsx
src/features/view-subdomains/SubdomainMetrics/SubdomainMetrics.tsx
src/features/view-subdomains/useSubdomainTableItem.ts
src/lib/constants/networks.ts
src/lib/hooks/index.ts
src/lib/hooks/useZAuctionCheckByBid.ts
src/lib/hooks/useZAuctionCheckByPaymentToken.ts

[Associated Notion Card](https://www.notion.so/zerotech/4985d8ec0c2f4eb4860678eec483e6f6?v=2de07237786c4d62830797da093e6a04&p=e8f97ba68e5542c3a43fea7f7ca26f16&pm=s)
-----
- testing
- bug fixes
Due to change in test nets, were unable to fully test the migrated flows and identify any bugs.
Each of the following flows have been tested and bug fixes have been implemented so each flow works and is successful as expected.
Transfer Ownership ✅
Cancel Bid ✅
Place Bid ✅
View Bids ✅
Accept Bid ✅

fix: end-to-end testing and bug fixes

---

package-lock.json
package.json

[Associated Notion Card](https://www.notion.so/zerotech/4985d8ec0c2f4eb4860678eec483e6f6?v=23ef4b88b0a94dc0adc9d345055b1c47&p=f25aa51f9a934400bc964b3317df9d56&pm=s)
-----
- bump utils package version `0.5.1` -> `0.5.2`

chore: bump utils package version `0.5.1` -> `0.5.2`

---

src/features/view-nft/Actions/Actions.tsx
src/features/view-subdomains/SubdomainTableCard/SubdomainTableCard.tsx
src/features/view-subdomains/useSubdomainTableItem.ts

[Associated Notion Card](https://www.notion.so/zerotech/4985d8ec0c2f4eb4860678eec483e6f6?v=7fd94d39937343aa983ac94b7d7034d5&p=781ee518648e4aa3a58dc7afdcb56783&pm=s)
-----
- bugfix / hotfix
[Loom description here](https://www.loom.com/share/e6330eaa7d6548e89a8245a16001c1e4)
Page no longer crashes when navigating through domains that have buy now set

hotfix: resolve invalid object errors 

---

src/features/create-dao/index.ts

[Associated Notion Card](https://www.notion.so/zerotech/4985d8ec0c2f4eb4860678eec483e6f6?v=7fd94d39937343aa983ac94b7d7034d5&p=f871ef6b13e247b3b18efd6ebfe1ea01&pm=s)
-----
- Bugfix
Tests were failing due to a missing export
Tests pass after removing missing export

fix: remove missing export CreateDAOButton to resolve failing tests

---

src/features/create-token/CreateTokenFormContext.tsx

[Associated Notion Card](https://www.notion.so/zerotech/4985d8ec0c2f4eb4860678eec483e6f6?v=40a33a299f3541f18ec40fbf914ba46f)
- Bugfix
This turned out to be a simple copy change. Issue resolved.

fix: amend create token wizard title

---

package-lock.json
package.json
src/App.tsx
src/features/create-dao/Steps/DAOSummary.tsx
src/features/create-dao/Steps/DetailsForm.tsx
src/features/view-subdomains/SubdomainTable/SubdomainTable.module.scss
src/features/view-subdomains/SubdomainTable/SubdomainTable.tsx
src/features/view-subdomains/SubdomainTable/useInfiniteSubdomains.ts
src/features/view-subdomains/SubdomainTable/useSubdomainSearch.ts
src/features/view-subdomains/SubdomainTableCard/SubdomainTableCard.tsx
src/features/view-subdomains/SubdomainTableRow/SubdomainTableRow.tsx
src/features/view-subdomains/ViewSubdomains.tsx
src/features/view-subdomains/useSubdomainTableItem.ts
src/lib/hooks/useCurrentRoute.ts
src/lib/hooks/useSubdomainData.ts
src/lib/hooks/useZna.ts

n/a
Feature
NFTs zApp retrieved subdomain data through Infura.
NFTs zApp retrieves subdomain data through the data store.
We will still need to switch some pages/components over to using the data store - this PR mostly focuses on the subdomain table.

feat: use data-store for subdomain data

---

package-lock.json
package.json
src/features/view-nft/Attributes/Attributes.module.scss
src/features/view-nft/Attributes/Attributes.tsx
src/features/view-nft/Attributes/index.ts
src/features/view-nft/index.ts
src/lib/hooks/index.ts
src/lib/hooks/useResize.ts
src/pages/NFT/NFT.tsx

[Associated Notion Card](https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-43&quickFilter=15)
-----
- Feature
Attributes section missing from NFT View page
Attributes section added.

feat: add attributes section - nft view

---

package-lock.json
package.json

- chore: bump version (`0.9.0`) -> (`0.10.0`)
- run `npm i`

chore: bump version (`0.9.0`) -> (`0.10.0`)

---

jest.setup.ts
src/features/view-subdomains/SubdomainTable/SubdomainTable.test.tsx
src/features/view-subdomains/SubdomainTable/SubdomainTable.tsx

[Jira ticket](https://wilderworld.atlassian.net/browse/ZAP-56?atlOrigin=eyJpIjoiM2I4YWFmNjkzMTUxNDg4MGEzYWQ0MzA1ODViMjlmNjAiLCJwIjoiaiJ9)

test(subdomain-table): add subdomain table tests

---

package-lock.json
package.json

chore: bump zui version

---

package-lock.json
package.json

- chore: bump version (`0.10.1`) -> (`0.11.0`)
- run `npm i` to update version number in `package-lock.json`

chore: bump version (`0.10.1`) -> (`0.11.0`)

---

package-lock.json
package.json
src/features/ui/Member/Member.module.scss
src/features/view-subdomains/DomainDetailsCard/DomainDetailsCard.module.scss

feat: label colors
